### ISSUE TITLE
Are different faces from the log messages implemented like for log4slime?

### ISSUE THREAD

**Issue by Dima-369** [40ants/log4sly#1]
From the README in https://github.com/7max/log4cl:

> The log output contains some headers in addition to the raw log message, such as the log level that message was submitted with, the time of the message as well as what looks like the name of the current package, and (If you have Log4Slime loaded and turned on), these headers use different faces from actual log message.

Is this ported as well into log4sly? I tried it out but the output face in the Sly MREPL is still `sly-mrepl-output-face`.

**Comment by svetlyak40wt** [comment]
No, different faces aren't supported under the SLY. If I recall correctly, that is because SLIME has "presentations" feature, but SLY doesn't.

If you'll will find a way how to colourize the output it would be cool.

However, for most of my projects, I redirect all logs to files to not overload REPL.

**Comment by Dima-369** [comment]
> If you'll will find a way how to colourize the output it would be cool.

It certainly is possible with https://github.com/PuercoPop/sly-repl-ansi-color

The code below prints a red foo in the REPL once `sly-repl-ansi-color` is setup:

```lisp
(format t "~c[31mfoo~c[0m~%" #\ESC #\ESC)
```

One can customize the output pattern of `log4cl` like this:

```lisp
;; add ~c[32m and ~c[0m around %m or any other color escape sequences
(log:config
 :pattern
 (format
  nil
  "%&%<%I%;<;;>;-5p [%D{%H:%M:%S}] %g{}{}{:downcase}%:; ;F (%C{}{ }{:downcase})%2.2N - %:_~c[32m%m~c[0m%>%n" 
  #\ESC  #\ESC))

(log:info "hi") ; print "hi" with a green foreground like <INFO> [16:18:31] cl-user () - hi
```

This has some examples on printing via ANSI color escape sequences: https://stackoverflow.com/a/62864580/6908755

---

To me this is already sufficient, I just wanted to colorize the actual log message content :)

**Comment by Dima-369** [comment]
And the approach above keeps the `sly-mrepl--output` face and just modifies the `font-lock-face`:

`(describe-char)` in Emacs on a colored character from the example above reports this:

```
There are text properties here:
  field                sly-mrepl--output
  font-lock-face       (foreground-color . "#98be65")
  fontified            t
  front-sticky         (read-only)
  read-only            t
```
